# 博客标题
title: "博客标题"
# 副标题
sub_title: "让我找到工作吧，求求了"
# 首页头像地址
avatar: "/images/avatar.png"

# 社交账号：如果是qq或者微信等，需要给别人一个加你的途径，比如扫描二维码进行添加,codeUrl处填写二维码，srcUrl填写链接地址
social:
    # 标题
  - name: "qq"
    # 图标地址
    icon: "/images/qq.svg"
    # 二维码图片
    codeUrl: "/images/qqFriend.jpg"
  - name: "微信"
    icon: "/images/wechat.svg"
    codeUrl: "/images/weixinFriend.jpg"
  - name: "github"
    icon: "/images/github.svg"
    srcUrl: "https://github.com/asdgjsad"

# 导航栏，这里的to里面的路由名字，应该与pages下面的文件名字保持一致
pages:
  - name: "文章"
    to: '/pages/article'
  - name: "标签"
    to: '/pages/tags'
  - name: "友链"
    to: '/pages/link'
  - name: "留言"
    to: '/pages/message'
  - name: "关于"
    to: '/pages/about'

# 友情链接
link:
  - name: "vitepress"
    url: "https://vitepress.dev/"
    imgSrc: "https://vitepress.dev/vitepress-logo-mini.png"
  - name: "vue"
    url: "https://cn.vuejs.org/"
    imgSrc: "https://cn.vuejs.org/logo.svg"
  - name: "lazychild"
    url: "https://www.lazychild.fun/"
    imgSrc: "https://asdgjsad.github.io/images/logo.jpg"

# 底部个人信息
footer_info:
  - title: "站长"
    info: "刘哲"
  - title: "联系方式"
    info: "17347187569"
  - title: "邮箱"
    info: "17347187569@163.com"

# 关于留言功能：目前只支持Valine, 需要到https://www.leancloud.cn/创建一个账号，创建完后，直接去控制台创建一个应用，去设置里面找到应用凭证即可
Valine:
  appId: ""
  appKey: ""
  placeholder: ""
  avatar: ""
  pageSize:

# 首页文章推荐
article_recommend:
  - title: "hello world"
    introduction: "欢迎你使用mg框架，作者: lazychild"
    tags: "hello"
    date: "2024-5-03"
    url: "/posts/hello.html"

# 底部外链接
extLinks:
  - leftText: "框架"
    rightText: "vitepress"
    bgColor: "7bed9f"
    href: "https://vitepress.dev/"
  - leftText: "存储"
    rightText: "github"
    bgColor: "e84393"
    href: "https://github.com/"
  - leftText: "留言"
    rightText: "valine"
    bgColor: "54a0ff"
    href: "https://valine.js.org/"